/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 128
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 8
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  sym_attribute_value = 10,
  sym_entity = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_quoted_attribute_value_token1 = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_quoted_attribute_value_token2 = 15,
  sym_text = 16,
  anon_sym_LT_BANG_DASH_DASH = 17,
  aux_sym_normal_comment_token1 = 18,
  aux_sym_normal_comment_token2 = 19,
  anon_sym_DASH_DASH_GT = 20,
  sym_include_keyword = 21,
  sym__text = 22,
  sym__start_tag_name = 23,
  sym__script_start_tag_name = 24,
  sym__style_start_tag_name = 25,
  sym__end_tag_name = 26,
  sym_erroneous_end_tag_name = 27,
  sym__implicit_end_tag = 28,
  sym_raw_text = 29,
  sym_document = 30,
  sym_doctype = 31,
  sym__node = 32,
  sym_element = 33,
  sym_script_element = 34,
  sym_style_element = 35,
  sym_start_tag = 36,
  sym_script_start_tag = 37,
  sym_style_start_tag = 38,
  sym_self_closing_tag = 39,
  sym_end_tag = 40,
  sym_attribute = 41,
  sym_quoted_attribute_value = 42,
  sym_comment = 43,
  sym_normal_comment = 44,
  sym_include_comment = 45,
  aux_sym_document_repeat1 = 46,
  aux_sym_start_tag_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [aux_sym_normal_comment_token1] = "normal_comment_token1",
  [aux_sym_normal_comment_token2] = "normal_comment_token2",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_include_keyword] = "include_keyword",
  [sym__text] = "_text",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_document] = "document",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_comment] = "comment",
  [sym_normal_comment] = "normal_comment",
  [sym_include_comment] = "include_comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [aux_sym_normal_comment_token1] = aux_sym_normal_comment_token1,
  [aux_sym_normal_comment_token2] = aux_sym_normal_comment_token2,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_include_keyword] = sym_include_keyword,
  [sym__text] = sym__text,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_document] = sym_document,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_comment] = sym_comment,
  [sym_normal_comment] = sym_normal_comment,
  [sym_include_comment] = sym_include_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_normal_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_normal_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_include_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_normal_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_include_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 19,
  [31] = 22,
  [32] = 18,
  [33] = 9,
  [34] = 20,
  [35] = 13,
  [36] = 21,
  [37] = 17,
  [38] = 23,
  [39] = 14,
  [40] = 24,
  [41] = 25,
  [42] = 26,
  [43] = 27,
  [44] = 28,
  [45] = 10,
  [46] = 16,
  [47] = 29,
  [48] = 15,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 50,
  [53] = 49,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 51,
  [61] = 59,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 55,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 62,
  [73] = 63,
  [74] = 71,
  [75] = 69,
  [76] = 67,
  [77] = 70,
  [78] = 78,
  [79] = 78,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 65,
  [84] = 84,
  [85] = 85,
  [86] = 66,
  [87] = 87,
  [88] = 64,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 81,
  [93] = 93,
  [94] = 85,
  [95] = 89,
  [96] = 96,
  [97] = 96,
  [98] = 80,
  [99] = 99,
  [100] = 82,
  [101] = 84,
  [102] = 99,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 103,
  [110] = 110,
  [111] = 111,
  [112] = 104,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 116,
  [118] = 118,
  [119] = 113,
  [120] = 108,
  [121] = 110,
  [122] = 105,
  [123] = 111,
  [124] = 115,
  [125] = 114,
  [126] = 118,
  [127] = 107,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '"', 84,
        '#', 14,
        '&', 4,
        '\'', 81,
        '-', 7,
        '/', 9,
        '<', 35,
        '=', 38,
        '>', 33,
        'D', 20,
        'd', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(84);
      if (lookahead == '\'') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(81);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(95);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '>') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(39);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(99);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 24:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(21);
      END_STATE();
    case 25:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 26:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == '#') ADVANCE(90);
      if (lookahead == '&') ADVANCE(4);
      if (lookahead == '<') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(30);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(83);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(91);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'd') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(101);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(93);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(87);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(88);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_normal_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_normal_comment_token2);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_normal_comment_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(97);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_include_keyword);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_include_keyword);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(94);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '^') ADVANCE(103);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '^') ADVANCE(103);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28, .external_lex_state = 2},
  [3] = {.lex_state = 28, .external_lex_state = 2},
  [4] = {.lex_state = 28, .external_lex_state = 2},
  [5] = {.lex_state = 28, .external_lex_state = 2},
  [6] = {.lex_state = 28, .external_lex_state = 2},
  [7] = {.lex_state = 28},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 28, .external_lex_state = 2},
  [10] = {.lex_state = 28, .external_lex_state = 2},
  [11] = {.lex_state = 28, .external_lex_state = 2},
  [12] = {.lex_state = 28, .external_lex_state = 2},
  [13] = {.lex_state = 28, .external_lex_state = 2},
  [14] = {.lex_state = 28, .external_lex_state = 2},
  [15] = {.lex_state = 28, .external_lex_state = 2},
  [16] = {.lex_state = 28, .external_lex_state = 2},
  [17] = {.lex_state = 28, .external_lex_state = 2},
  [18] = {.lex_state = 28, .external_lex_state = 2},
  [19] = {.lex_state = 28, .external_lex_state = 2},
  [20] = {.lex_state = 28, .external_lex_state = 2},
  [21] = {.lex_state = 28, .external_lex_state = 2},
  [22] = {.lex_state = 28, .external_lex_state = 2},
  [23] = {.lex_state = 28, .external_lex_state = 2},
  [24] = {.lex_state = 28, .external_lex_state = 2},
  [25] = {.lex_state = 28, .external_lex_state = 2},
  [26] = {.lex_state = 28, .external_lex_state = 2},
  [27] = {.lex_state = 28, .external_lex_state = 2},
  [28] = {.lex_state = 28, .external_lex_state = 2},
  [29] = {.lex_state = 28, .external_lex_state = 2},
  [30] = {.lex_state = 28},
  [31] = {.lex_state = 28},
  [32] = {.lex_state = 28},
  [33] = {.lex_state = 28},
  [34] = {.lex_state = 28},
  [35] = {.lex_state = 28},
  [36] = {.lex_state = 28},
  [37] = {.lex_state = 28},
  [38] = {.lex_state = 28},
  [39] = {.lex_state = 28},
  [40] = {.lex_state = 28},
  [41] = {.lex_state = 28},
  [42] = {.lex_state = 28},
  [43] = {.lex_state = 28},
  [44] = {.lex_state = 28},
  [45] = {.lex_state = 28},
  [46] = {.lex_state = 28},
  [47] = {.lex_state = 28},
  [48] = {.lex_state = 28},
  [49] = {.lex_state = 8, .external_lex_state = 3},
  [50] = {.lex_state = 8, .external_lex_state = 3},
  [51] = {.lex_state = 8, .external_lex_state = 3},
  [52] = {.lex_state = 8, .external_lex_state = 3},
  [53] = {.lex_state = 8, .external_lex_state = 3},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8, .external_lex_state = 3},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 96},
  [63] = {.lex_state = 0, .external_lex_state = 4},
  [64] = {.lex_state = 8, .external_lex_state = 3},
  [65] = {.lex_state = 8, .external_lex_state = 3},
  [66] = {.lex_state = 8, .external_lex_state = 3},
  [67] = {.lex_state = 96},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 96},
  [70] = {.lex_state = 0, .external_lex_state = 5},
  [71] = {.lex_state = 0, .external_lex_state = 4},
  [72] = {.lex_state = 96},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 96},
  [76] = {.lex_state = 96},
  [77] = {.lex_state = 0, .external_lex_state = 5},
  [78] = {.lex_state = 3},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 102},
  [81] = {.lex_state = 102},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 8},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 8},
  [87] = {.lex_state = 0, .external_lex_state = 4},
  [88] = {.lex_state = 8},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0, .external_lex_state = 4},
  [91] = {.lex_state = 0, .external_lex_state = 4},
  [92] = {.lex_state = 102},
  [93] = {.lex_state = 0, .external_lex_state = 4},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 102},
  [97] = {.lex_state = 102},
  [98] = {.lex_state = 102},
  [99] = {.lex_state = 102},
  [100] = {.lex_state = 5},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 102},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 26},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0, .external_lex_state = 6},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 26},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0, .external_lex_state = 6},
  [127] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [sym_include_keyword] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(106),
    [sym_doctype] = STATE(7),
    [sym__node] = STATE(7),
    [sym_element] = STATE(7),
    [sym_script_element] = STATE(7),
    [sym_style_element] = STATE(7),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(63),
    [sym_style_start_tag] = STATE(71),
    [sym_self_closing_tag] = STATE(47),
    [sym_comment] = STATE(7),
    [sym_normal_comment] = STATE(35),
    [sym_include_comment] = STATE(35),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_BANG] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [sym_entity] = ACTIONS(9),
    [sym_text] = ACTIONS(11),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(13),
    [sym_include_keyword] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(21), 1,
      sym_entity,
    ACTIONS(25), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(27), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(39), 1,
      sym_end_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(74), 1,
      sym_style_start_tag,
    ACTIONS(23), 2,
      sym_text,
      sym_include_keyword,
    STATE(13), 2,
      sym_normal_comment,
      sym_include_comment,
    STATE(3), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_comment,
      aux_sym_document_repeat1,
  [51] = 14,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(25), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(29), 1,
      sym_entity,
    ACTIONS(33), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(34), 1,
      sym_end_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(74), 1,
      sym_style_start_tag,
    ACTIONS(31), 2,
      sym_text,
      sym_include_keyword,
    STATE(13), 2,
      sym_normal_comment,
      sym_include_comment,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_comment,
      aux_sym_document_repeat1,
  [102] = 14,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    ACTIONS(37), 1,
      sym_entity,
    ACTIONS(41), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(14), 1,
      sym_end_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(74), 1,
      sym_style_start_tag,
    ACTIONS(39), 2,
      sym_text,
      sym_include_keyword,
    STATE(13), 2,
      sym_normal_comment,
      sym_include_comment,
    STATE(5), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_comment,
      aux_sym_document_repeat1,
  [153] = 14,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(29), 1,
      sym_entity,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    ACTIONS(43), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(20), 1,
      sym_end_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(74), 1,
      sym_style_start_tag,
    ACTIONS(31), 2,
      sym_text,
      sym_include_keyword,
    STATE(13), 2,
      sym_normal_comment,
      sym_include_comment,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_comment,
      aux_sym_document_repeat1,
  [204] = 12,
    ACTIONS(45), 1,
      anon_sym_LT_BANG,
    ACTIONS(48), 1,
      anon_sym_LT,
    ACTIONS(53), 1,
      sym_entity,
    ACTIONS(59), 1,
      anon_sym_LT_BANG_DASH_DASH,
    STATE(4), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(74), 1,
      sym_style_start_tag,
    ACTIONS(51), 2,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
    ACTIONS(56), 2,
      sym_text,
      sym_include_keyword,
    STATE(13), 2,
      sym_normal_comment,
      sym_include_comment,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_comment,
      aux_sym_document_repeat1,
  [250] = 12,
    ACTIONS(5), 1,
      anon_sym_LT_BANG,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_entity,
    STATE(2), 1,
      sym_start_tag,
    STATE(47), 1,
      sym_self_closing_tag,
    STATE(63), 1,
      sym_script_start_tag,
    STATE(71), 1,
      sym_style_start_tag,
    ACTIONS(66), 2,
      sym_text,
      sym_include_keyword,
    STATE(35), 2,
      sym_normal_comment,
      sym_include_comment,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_comment,
      aux_sym_document_repeat1,
  [295] = 12,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      anon_sym_LT_BANG,
    ACTIONS(71), 1,
      anon_sym_LT,
    ACTIONS(74), 1,
      sym_entity,
    ACTIONS(80), 1,
      anon_sym_LT_BANG_DASH_DASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(47), 1,
      sym_self_closing_tag,
    STATE(63), 1,
      sym_script_start_tag,
    STATE(71), 1,
      sym_style_start_tag,
    ACTIONS(77), 2,
      sym_text,
      sym_include_keyword,
    STATE(35), 2,
      sym_normal_comment,
      sym_include_comment,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_comment,
      aux_sym_document_repeat1,
  [340] = 2,
    ACTIONS(83), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(85), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [353] = 2,
    ACTIONS(87), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(89), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [366] = 2,
    ACTIONS(91), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(93), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [379] = 2,
    ACTIONS(95), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(97), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [392] = 2,
    ACTIONS(99), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(101), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [405] = 2,
    ACTIONS(103), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(105), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [418] = 2,
    ACTIONS(107), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(109), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [431] = 2,
    ACTIONS(111), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(113), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [444] = 2,
    ACTIONS(115), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(117), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [457] = 2,
    ACTIONS(119), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(121), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [470] = 2,
    ACTIONS(123), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(125), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [483] = 2,
    ACTIONS(127), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(129), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [496] = 2,
    ACTIONS(131), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(133), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [509] = 2,
    ACTIONS(135), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(137), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [522] = 2,
    ACTIONS(139), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(141), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [535] = 2,
    ACTIONS(143), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(145), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [548] = 2,
    ACTIONS(147), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(149), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [561] = 2,
    ACTIONS(151), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(153), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [574] = 2,
    ACTIONS(155), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(157), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [587] = 2,
    ACTIONS(159), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(161), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [600] = 2,
    ACTIONS(163), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
    ACTIONS(165), 4,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
  [613] = 2,
    ACTIONS(125), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(123), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [625] = 2,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(135), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [637] = 2,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(119), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [649] = 2,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(83), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [661] = 2,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(127), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [673] = 2,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(99), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [685] = 2,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(131), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [697] = 2,
    ACTIONS(117), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(115), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [709] = 2,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(139), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [721] = 2,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(103), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [733] = 2,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(143), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [745] = 2,
    ACTIONS(149), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(147), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [757] = 2,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(151), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [769] = 2,
    ACTIONS(157), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(155), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [781] = 2,
    ACTIONS(161), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(159), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [793] = 2,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(87), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [805] = 2,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(111), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [817] = 2,
    ACTIONS(165), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(163), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [829] = 2,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      sym_entity,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(107), 4,
      anon_sym_LT_BANG,
      anon_sym_LT,
      sym_text,
      sym_include_keyword,
  [841] = 4,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_SLASH_GT,
    ACTIONS(171), 1,
      sym_attribute_name,
    STATE(51), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [855] = 4,
    ACTIONS(171), 1,
      sym_attribute_name,
    ACTIONS(173), 1,
      anon_sym_GT,
    ACTIONS(175), 1,
      anon_sym_SLASH_GT,
    STATE(49), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [869] = 3,
    ACTIONS(179), 1,
      sym_attribute_name,
    ACTIONS(177), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(51), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [881] = 4,
    ACTIONS(171), 1,
      sym_attribute_name,
    ACTIONS(173), 1,
      anon_sym_GT,
    ACTIONS(182), 1,
      anon_sym_SLASH_GT,
    STATE(53), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [895] = 4,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(171), 1,
      sym_attribute_name,
    ACTIONS(184), 1,
      anon_sym_SLASH_GT,
    STATE(51), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [909] = 3,
    ACTIONS(186), 1,
      anon_sym_GT,
    ACTIONS(188), 1,
      sym_attribute_name,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [920] = 2,
    ACTIONS(192), 1,
      anon_sym_EQ,
    ACTIONS(190), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [929] = 3,
    ACTIONS(188), 1,
      sym_attribute_name,
    ACTIONS(194), 1,
      anon_sym_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [940] = 3,
    ACTIONS(188), 1,
      sym_attribute_name,
    ACTIONS(196), 1,
      anon_sym_GT,
    STATE(58), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [951] = 3,
    ACTIONS(188), 1,
      sym_attribute_name,
    ACTIONS(198), 1,
      anon_sym_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [962] = 4,
    ACTIONS(200), 1,
      sym_attribute_value,
    ACTIONS(202), 1,
      anon_sym_SQUOTE,
    ACTIONS(204), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_quoted_attribute_value,
  [975] = 3,
    ACTIONS(177), 1,
      anon_sym_GT,
    ACTIONS(206), 1,
      sym_attribute_name,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [986] = 4,
    ACTIONS(209), 1,
      sym_attribute_value,
    ACTIONS(211), 1,
      anon_sym_SQUOTE,
    ACTIONS(213), 1,
      anon_sym_DQUOTE,
    STATE(83), 1,
      sym_quoted_attribute_value,
  [999] = 3,
    ACTIONS(215), 1,
      aux_sym_normal_comment_token1,
    ACTIONS(217), 1,
      aux_sym_normal_comment_token2,
    ACTIONS(219), 1,
      sym_include_keyword,
  [1009] = 3,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(221), 1,
      sym_raw_text,
    STATE(48), 1,
      sym_end_tag,
  [1019] = 1,
    ACTIONS(223), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1025] = 1,
    ACTIONS(225), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1031] = 1,
    ACTIONS(227), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1037] = 3,
    ACTIONS(229), 1,
      aux_sym_normal_comment_token1,
    ACTIONS(231), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(233), 1,
      sym__text,
  [1047] = 2,
    ACTIONS(235), 1,
      anon_sym_EQ,
    ACTIONS(190), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1055] = 3,
    ACTIONS(237), 1,
      aux_sym_normal_comment_token1,
    ACTIONS(239), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(241), 1,
      sym__text,
  [1065] = 3,
    ACTIONS(243), 1,
      sym__start_tag_name,
    ACTIONS(245), 1,
      sym__script_start_tag_name,
    ACTIONS(247), 1,
      sym__style_start_tag_name,
  [1075] = 3,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(249), 1,
      sym_raw_text,
    STATE(46), 1,
      sym_end_tag,
  [1085] = 3,
    ACTIONS(251), 1,
      aux_sym_normal_comment_token1,
    ACTIONS(253), 1,
      aux_sym_normal_comment_token2,
    ACTIONS(255), 1,
      sym_include_keyword,
  [1095] = 3,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    ACTIONS(257), 1,
      sym_raw_text,
    STATE(15), 1,
      sym_end_tag,
  [1105] = 3,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    ACTIONS(259), 1,
      sym_raw_text,
    STATE(16), 1,
      sym_end_tag,
  [1115] = 3,
    ACTIONS(261), 1,
      aux_sym_normal_comment_token1,
    ACTIONS(263), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(265), 1,
      sym__text,
  [1125] = 3,
    ACTIONS(267), 1,
      aux_sym_normal_comment_token1,
    ACTIONS(269), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(271), 1,
      sym__text,
  [1135] = 3,
    ACTIONS(245), 1,
      sym__script_start_tag_name,
    ACTIONS(247), 1,
      sym__style_start_tag_name,
    ACTIONS(273), 1,
      sym__start_tag_name,
  [1145] = 2,
    ACTIONS(275), 1,
      aux_sym_normal_comment_token2,
    ACTIONS(277), 1,
      sym_include_keyword,
  [1152] = 2,
    ACTIONS(279), 1,
      aux_sym_normal_comment_token2,
    ACTIONS(281), 1,
      sym_include_keyword,
  [1159] = 2,
    ACTIONS(231), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(283), 1,
      sym__text,
  [1166] = 2,
    ACTIONS(285), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(287), 1,
      sym__text,
  [1173] = 2,
    ACTIONS(289), 1,
      anon_sym_SQUOTE,
    ACTIONS(291), 1,
      aux_sym_quoted_attribute_value_token1,
  [1180] = 1,
    ACTIONS(225), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1185] = 2,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
    ACTIONS(293), 1,
      aux_sym_quoted_attribute_value_token2,
  [1192] = 2,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(36), 1,
      sym_end_tag,
  [1199] = 1,
    ACTIONS(227), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1204] = 1,
    ACTIONS(295), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1209] = 1,
    ACTIONS(223), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1214] = 2,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(31), 1,
      sym_end_tag,
  [1221] = 1,
    ACTIONS(297), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1226] = 1,
    ACTIONS(299), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1231] = 2,
    ACTIONS(301), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(303), 1,
      sym__text,
  [1238] = 1,
    ACTIONS(305), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1243] = 2,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    STATE(21), 1,
      sym_end_tag,
  [1250] = 2,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    STATE(22), 1,
      sym_end_tag,
  [1257] = 2,
    ACTIONS(307), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(309), 1,
      sym__text,
  [1264] = 2,
    ACTIONS(311), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(313), 1,
      sym__text,
  [1271] = 2,
    ACTIONS(269), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(315), 1,
      sym__text,
  [1278] = 2,
    ACTIONS(317), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(319), 1,
      sym__text,
  [1285] = 2,
    ACTIONS(321), 1,
      anon_sym_SQUOTE,
    ACTIONS(323), 1,
      aux_sym_quoted_attribute_value_token1,
  [1292] = 2,
    ACTIONS(321), 1,
      anon_sym_DQUOTE,
    ACTIONS(325), 1,
      aux_sym_quoted_attribute_value_token2,
  [1299] = 2,
    ACTIONS(327), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(329), 1,
      sym__text,
  [1306] = 1,
    ACTIONS(331), 1,
      anon_sym_DASH_DASH_GT,
  [1310] = 1,
    ACTIONS(333), 1,
      anon_sym_GT,
  [1314] = 1,
    ACTIONS(335), 1,
      anon_sym_GT,
  [1318] = 1,
    ACTIONS(337), 1,
      ts_builtin_sym_end,
  [1322] = 1,
    ACTIONS(339), 1,
      sym__doctype,
  [1326] = 1,
    ACTIONS(341), 1,
      anon_sym_SQUOTE,
  [1330] = 1,
    ACTIONS(343), 1,
      anon_sym_DASH_DASH_GT,
  [1334] = 1,
    ACTIONS(341), 1,
      anon_sym_DQUOTE,
  [1338] = 1,
    ACTIONS(345), 1,
      anon_sym_DASH_DASH_GT,
  [1342] = 1,
    ACTIONS(347), 1,
      anon_sym_GT,
  [1346] = 1,
    ACTIONS(349), 1,
      anon_sym_DASH_DASH_GT,
  [1350] = 1,
    ACTIONS(351), 1,
      anon_sym_DASH_DASH_GT,
  [1354] = 1,
    ACTIONS(353), 1,
      aux_sym_doctype_token1,
  [1358] = 1,
    ACTIONS(355), 1,
      anon_sym_DASH_DASH_GT,
  [1362] = 1,
    ACTIONS(357), 1,
      anon_sym_DASH_DASH_GT,
  [1366] = 1,
    ACTIONS(359), 1,
      sym__end_tag_name,
  [1370] = 1,
    ACTIONS(361), 1,
      anon_sym_DASH_DASH_GT,
  [1374] = 1,
    ACTIONS(363), 1,
      anon_sym_SQUOTE,
  [1378] = 1,
    ACTIONS(363), 1,
      anon_sym_DQUOTE,
  [1382] = 1,
    ACTIONS(365), 1,
      anon_sym_GT,
  [1386] = 1,
    ACTIONS(367), 1,
      anon_sym_DASH_DASH_GT,
  [1390] = 1,
    ACTIONS(369), 1,
      aux_sym_doctype_token1,
  [1394] = 1,
    ACTIONS(371), 1,
      anon_sym_DASH_DASH_GT,
  [1398] = 1,
    ACTIONS(373), 1,
      sym__end_tag_name,
  [1402] = 1,
    ACTIONS(375), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 153,
  [SMALL_STATE(6)] = 204,
  [SMALL_STATE(7)] = 250,
  [SMALL_STATE(8)] = 295,
  [SMALL_STATE(9)] = 340,
  [SMALL_STATE(10)] = 353,
  [SMALL_STATE(11)] = 366,
  [SMALL_STATE(12)] = 379,
  [SMALL_STATE(13)] = 392,
  [SMALL_STATE(14)] = 405,
  [SMALL_STATE(15)] = 418,
  [SMALL_STATE(16)] = 431,
  [SMALL_STATE(17)] = 444,
  [SMALL_STATE(18)] = 457,
  [SMALL_STATE(19)] = 470,
  [SMALL_STATE(20)] = 483,
  [SMALL_STATE(21)] = 496,
  [SMALL_STATE(22)] = 509,
  [SMALL_STATE(23)] = 522,
  [SMALL_STATE(24)] = 535,
  [SMALL_STATE(25)] = 548,
  [SMALL_STATE(26)] = 561,
  [SMALL_STATE(27)] = 574,
  [SMALL_STATE(28)] = 587,
  [SMALL_STATE(29)] = 600,
  [SMALL_STATE(30)] = 613,
  [SMALL_STATE(31)] = 625,
  [SMALL_STATE(32)] = 637,
  [SMALL_STATE(33)] = 649,
  [SMALL_STATE(34)] = 661,
  [SMALL_STATE(35)] = 673,
  [SMALL_STATE(36)] = 685,
  [SMALL_STATE(37)] = 697,
  [SMALL_STATE(38)] = 709,
  [SMALL_STATE(39)] = 721,
  [SMALL_STATE(40)] = 733,
  [SMALL_STATE(41)] = 745,
  [SMALL_STATE(42)] = 757,
  [SMALL_STATE(43)] = 769,
  [SMALL_STATE(44)] = 781,
  [SMALL_STATE(45)] = 793,
  [SMALL_STATE(46)] = 805,
  [SMALL_STATE(47)] = 817,
  [SMALL_STATE(48)] = 829,
  [SMALL_STATE(49)] = 841,
  [SMALL_STATE(50)] = 855,
  [SMALL_STATE(51)] = 869,
  [SMALL_STATE(52)] = 881,
  [SMALL_STATE(53)] = 895,
  [SMALL_STATE(54)] = 909,
  [SMALL_STATE(55)] = 920,
  [SMALL_STATE(56)] = 929,
  [SMALL_STATE(57)] = 940,
  [SMALL_STATE(58)] = 951,
  [SMALL_STATE(59)] = 962,
  [SMALL_STATE(60)] = 975,
  [SMALL_STATE(61)] = 986,
  [SMALL_STATE(62)] = 999,
  [SMALL_STATE(63)] = 1009,
  [SMALL_STATE(64)] = 1019,
  [SMALL_STATE(65)] = 1025,
  [SMALL_STATE(66)] = 1031,
  [SMALL_STATE(67)] = 1037,
  [SMALL_STATE(68)] = 1047,
  [SMALL_STATE(69)] = 1055,
  [SMALL_STATE(70)] = 1065,
  [SMALL_STATE(71)] = 1075,
  [SMALL_STATE(72)] = 1085,
  [SMALL_STATE(73)] = 1095,
  [SMALL_STATE(74)] = 1105,
  [SMALL_STATE(75)] = 1115,
  [SMALL_STATE(76)] = 1125,
  [SMALL_STATE(77)] = 1135,
  [SMALL_STATE(78)] = 1145,
  [SMALL_STATE(79)] = 1152,
  [SMALL_STATE(80)] = 1159,
  [SMALL_STATE(81)] = 1166,
  [SMALL_STATE(82)] = 1173,
  [SMALL_STATE(83)] = 1180,
  [SMALL_STATE(84)] = 1185,
  [SMALL_STATE(85)] = 1192,
  [SMALL_STATE(86)] = 1199,
  [SMALL_STATE(87)] = 1204,
  [SMALL_STATE(88)] = 1209,
  [SMALL_STATE(89)] = 1214,
  [SMALL_STATE(90)] = 1221,
  [SMALL_STATE(91)] = 1226,
  [SMALL_STATE(92)] = 1231,
  [SMALL_STATE(93)] = 1238,
  [SMALL_STATE(94)] = 1243,
  [SMALL_STATE(95)] = 1250,
  [SMALL_STATE(96)] = 1257,
  [SMALL_STATE(97)] = 1264,
  [SMALL_STATE(98)] = 1271,
  [SMALL_STATE(99)] = 1278,
  [SMALL_STATE(100)] = 1285,
  [SMALL_STATE(101)] = 1292,
  [SMALL_STATE(102)] = 1299,
  [SMALL_STATE(103)] = 1306,
  [SMALL_STATE(104)] = 1310,
  [SMALL_STATE(105)] = 1314,
  [SMALL_STATE(106)] = 1318,
  [SMALL_STATE(107)] = 1322,
  [SMALL_STATE(108)] = 1326,
  [SMALL_STATE(109)] = 1330,
  [SMALL_STATE(110)] = 1334,
  [SMALL_STATE(111)] = 1338,
  [SMALL_STATE(112)] = 1342,
  [SMALL_STATE(113)] = 1346,
  [SMALL_STATE(114)] = 1350,
  [SMALL_STATE(115)] = 1354,
  [SMALL_STATE(116)] = 1358,
  [SMALL_STATE(117)] = 1362,
  [SMALL_STATE(118)] = 1366,
  [SMALL_STATE(119)] = 1370,
  [SMALL_STATE(120)] = 1374,
  [SMALL_STATE(121)] = 1378,
  [SMALL_STATE(122)] = 1382,
  [SMALL_STATE(123)] = 1386,
  [SMALL_STATE(124)] = 1390,
  [SMALL_STATE(125)] = 1394,
  [SMALL_STATE(126)] = 1398,
  [SMALL_STATE(127)] = 1402,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(127),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_comment, 6, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_comment, 6, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_normal_comment, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_comment, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_comment, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_comment, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_normal_comment, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_comment, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_comment, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_comment, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_normal_comment, 5, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_normal_comment, 5, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_comment, 5, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_comment, 5, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [317] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [337] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
  },
  [2] = {
    [ts_external_token__implicit_end_tag] = true,
  },
  [3] = {
    [ts_external_token_SLASH_GT] = true,
  },
  [4] = {
    [ts_external_token_raw_text] = true,
  },
  [5] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
  },
  [6] = {
    [ts_external_token__end_tag_name] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "html",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
